[server]
id = "eternity"
content_id = "eternity"

[game]
hostname = "The Estate"
desc = "Bloom rises from Orravion's shoreline like a glassy mirage. Offshore thunder rolls through the skyline as if the city itself is breathing. It's safe here, for for those who can afford it."
role_timers = false
auto_eat_drinks = true
auto_eat_food = true
loadouts_points = 30
traits_default_points = 20
traits_max = 25
defaultpreset = "breakhome"
lobbyduration = 30
maxcharacterslots = 100

[vote]
autovote_enabled = false

[chat]
max_message_length = 30000

[atmos]
space_wind = false

[reclaimer]
allow_gibbing = false

[shuttle]
auto_call_time = 0
emergency = false
arrivals = false

[replay]
server_recording_enabled = false
client_recording_enabled = false

[status]
enabled = true

[hub]
advertise = false
tags = "18+,lang:en-US,rp:med,region:am_n_e,no_tag_infer"

[console]
loginlocal = true

[net]
tickrate = 30
port = 1212
bindto = "::,0.0.0.0"
max_connections = 256

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false
